name: iOS build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Generate release tag
      id: tag
      run: echo "::set-output name=release_tag::giavang_$(date +"%Y-%m-%d_%H.%M")"

    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: find . -name *Runner.app*
    - run: ls -la ./build/ios/iphoneos/Runner.app
    - run: ls -la ./build/ios/iphoneos
    - run: ls -la ./build/ios/Release-iphoneos/Runner.app
    - run: ls -la ./build/ios/Release-iphoneos
    #- uses: softprops/action-gh-release@v1
      #with:
        #tag_name: ${{ steps.tag.outputs.release_tag }}
        #files: ./build/ios/iphoneos/Runner.app/*
      #env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
